version: 2
multi-ecosystem-groups:
  application-dependencies:
    schedule:
      interval: weekly

updates:
  - package-ecosystem: npm
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: application-dependencies
    target-branch: main

  - package-ecosystem: cargo
    directory: "/src-tauri"
    patterns: ["*"]
    multi-ecosystem-group: application-dependencies
    target-branch: main

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    target-branch: main
